# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed0e0b7468e367fa046b6fc21301e948747848b60108b2e2e4f405682f8abc03f4bd93c50648f2a45367261d48b7b8407366c6c43becf9f3394aa58f25a500b6

test:
  secret_key_base: 46cbe74cb1a77f2904ac673edc2b7e43ca1964cc995185f17990e1ba1acefd0678f647c5f384c7c7505cb802cfd5ae40e92c2dd723c85f1cd4d4be10aae85e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
